# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alacritty = {
    pname = "alacritty";
    version = "94800165c13998b600a9da9d29c330de9f28618e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "alacritty";
      rev = "94800165c13998b600a9da9d29c330de9f28618e";
      fetchSubmodules = false;
      sha256 = "sha256-Pi1Hicv3wPALGgqurdTzXEzJNx7vVh+8B9tlqhRpR2Y=";
    };
    date = "2024-04-09";
  };
  bat = {
    pname = "bat";
    version = "d714cc1d358ea51bfc02550dabab693f70cccea0";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bat";
      rev = "d714cc1d358ea51bfc02550dabab693f70cccea0";
      fetchSubmodules = false;
      sha256 = "sha256-Q5B4NDrfCIK3UAMs94vdXnR42k4AXCqZz6sRn8bzmf4=";
    };
    date = "2024-04-25";
  };
  bottom = {
    pname = "bottom";
    version = "66c540ea512187df5f0c6c97312b0c6da7225af0";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bottom";
      rev = "66c540ea512187df5f0c6c97312b0c6da7225af0";
      fetchSubmodules = false;
      sha256 = "sha256-Ge2avQXFWEqGPOglJBnH6bjejFGfCyLOqrYcaoAP0XI=";
    };
    date = "2024-05-13";
  };
  btop = {
    pname = "btop";
    version = "21b8d5956a8b07fa52519e3267fb3a2d2e693d17";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "btop";
      rev = "21b8d5956a8b07fa52519e3267fb3a2d2e693d17";
      fetchSubmodules = false;
      sha256 = "sha256-UXeTypc15MhjgGUiCrDUZ40m32yH2o1N+rcrEgY6sME=";
    };
    date = "2024-05-14";
  };
  cava = {
    pname = "cava";
    version = "6ec25ba688e30f3e5d6004ef6a295e6ba90c64d4";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "cava";
      rev = "6ec25ba688e30f3e5d6004ef6a295e6ba90c64d4";
      fetchSubmodules = false;
      sha256 = "sha256-1+CCUaf8U/NH/eHuYRbQo8inbhSMJ3vji6UH52hrF1s=";
    };
    date = "2024-05-25";
  };
  delta = {
    pname = "delta";
    version = "765eb17d0268bf07c20ca439771153f8bc79444f";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "delta";
      rev = "765eb17d0268bf07c20ca439771153f8bc79444f";
      fetchSubmodules = false;
      sha256 = "sha256-GA0n9obZlD0Y2rAbGMjcdJ5I0ij1NEPBFC7rv7J49QI=";
    };
    date = "2024-03-23";
  };
  dunst = {
    pname = "dunst";
    version = "bfec91a5d0ab02a73a4615243feb5499d376831c";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "dunst";
      rev = "bfec91a5d0ab02a73a4615243feb5499d376831c";
      fetchSubmodules = false;
      sha256 = "sha256-xy99DpBrOKlP7DgKyPgbl4QGC+dnXnvkGlkIG0cmd2A=";
    };
    date = "2024-04-07";
  };
  fcitx5 = {
    pname = "fcitx5";
    version = "ce244cfdf43a648d984719fdfd1d60aab09f5c97";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fcitx5";
      rev = "ce244cfdf43a648d984719fdfd1d60aab09f5c97";
      fetchSubmodules = false;
      sha256 = "sha256-uFaCbyrEjv4oiKUzLVFzw+UY54/h7wh2cntqeyYwGps=";
    };
    date = "2022-10-05";
  };
  fish = {
    pname = "fish";
    version = "a3b9eb5eaf2171ba1359fe98f20d226c016568cf";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fish";
      rev = "a3b9eb5eaf2171ba1359fe98f20d226c016568cf";
      fetchSubmodules = false;
      sha256 = "sha256-shQxlyoauXJACoZWtRUbRMxmm10R8vOigXwjxBhG8ng=";
    };
    date = "2024-05-14";
  };
  foot = {
    pname = "foot";
    version = "80756a4d63ea4fae4d0fdd793017370f8b8b12ac";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "foot";
      rev = "80756a4d63ea4fae4d0fdd793017370f8b8b12ac";
      fetchSubmodules = false;
      sha256 = "sha256-h6+7ln/i+FRSfWX2aSLhrxFO4mYJgH2pzzhe2Zz9Q4k=";
    };
    date = "2024-06-06";
  };
  gh-dash = {
    pname = "gh-dash";
    version = "a971447dbb6e43c274ce52697c0bd381735c3c8a";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "gh-dash";
      rev = "a971447dbb6e43c274ce52697c0bd381735c3c8a";
      fetchSubmodules = false;
      sha256 = "sha256-zbFOjg097LN+FRsagnYOdfaDb0tGNJPYkoxTbYK/4HA=";
    };
    date = "2024-04-27";
  };
  gitui = {
    pname = "gitui";
    version = "c7661f043cb6773a1fc96c336738c6399de3e617";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "gitui";
      rev = "c7661f043cb6773a1fc96c336738c6399de3e617";
      fetchSubmodules = false;
      sha256 = "sha256-CRxpEDShQcCEYtSXwLV5zFB8u0HVcudNcMruPyrnSEk=";
    };
    date = "2024-05-25";
  };
  glamour = {
    pname = "glamour";
    version = "66d7b09325af67b1c5cdb063343e829c04ad7d5f";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "glamour";
      rev = "66d7b09325af67b1c5cdb063343e829c04ad7d5f";
      fetchSubmodules = false;
      sha256 = "sha256-f3JFgqL3K/u8U/UzmBohJLDBPlT446bosRQDca9+4oA=";
    };
    date = "2024-04-02";
  };
  grub = {
    pname = "grub";
    version = "88f6124757331fd3a37c8a69473021389b7663ad";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "grub";
      rev = "88f6124757331fd3a37c8a69473021389b7663ad";
      fetchSubmodules = false;
      sha256 = "sha256-e8XFWebd/GyX44WQI06Cx6sOduCZc5z7/YhweVQGMGY=";
    };
    date = "2024-03-07";
  };
  gtk = {
    pname = "gtk";
    version = "23b52b5b9cde1e11c07315e79a55804d2ac77e3a";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "gtk";
      rev = "23b52b5b9cde1e11c07315e79a55804d2ac77e3a";
      fetchSubmodules = false;
      sha256 = "sha256-4tBGN+Rra6C2pjkoLWmNqaYUwpzALsYrn4tkYGUtQl4=";
    };
    date = "2024-06-02";
  };
  helix = {
    pname = "helix";
    version = "bbbc0873238ac8979fb11748b322b61507317d50";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "helix";
      rev = "bbbc0873238ac8979fb11748b322b61507317d50";
      fetchSubmodules = false;
      sha256 = "sha256-eukktvsgW881pHmfWcngFHe9UsIO54/v9VFz49GqGcc=";
    };
    date = "2024-06-07";
  };
  hyprland = {
    pname = "hyprland";
    version = "c388ac55563ddeea0afe9df79d4bfff0096b146b";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "hyprland";
      rev = "c388ac55563ddeea0afe9df79d4bfff0096b146b";
      fetchSubmodules = false;
      sha256 = "sha256-xSa/z0Pu+ioZ0gFH9qSo9P94NPkEMovstm1avJ7rvzM=";
    };
    date = "2024-06-19";
  };
  imv = {
    pname = "imv";
    version = "0317a097b6ec8122b1da6d02f61d0c5158019f6e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "imv";
      rev = "0317a097b6ec8122b1da6d02f61d0c5158019f6e";
      fetchSubmodules = false;
      sha256 = "sha256-n6obxM5iVSOdlGdI8ZEmYuxudarLoZHqGETrpTcdrok=";
    };
    date = "2024-01-17";
  };
  k9s = {
    pname = "k9s";
    version = "e08b9302aee2b7193d6fcc3a9ffd2f24d2957dbf";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "k9s";
      rev = "e08b9302aee2b7193d6fcc3a9ffd2f24d2957dbf";
      fetchSubmodules = false;
      sha256 = "sha256-tg+xFNj9wkWFcD9bXDor/VCZVosoAH+8grz5FY5QgnM=";
    };
    date = "2024-05-31";
  };
  kitty = {
    pname = "kitty";
    version = "1f99e6682d84fe4d8e3177d3add8d0591607a2ac";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "kitty";
      rev = "1f99e6682d84fe4d8e3177d3add8d0591607a2ac";
      fetchSubmodules = false;
      sha256 = "sha256-Y51wmGRYDjxbgO/g66+aBA+uOVrQpv2rQIjxbuzm0uk=";
    };
    date = "2024-06-01";
  };
  lazygit = {
    pname = "lazygit";
    version = "21a25afd92327ddea8446ab9171ca7039b431e9e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "lazygit";
      rev = "21a25afd92327ddea8446ab9171ca7039b431e9e";
      fetchSubmodules = false;
      sha256 = "sha256-jQjg4YHIj321+dLoCxI0bjf2QYKvpINwqeicx9vqZmE=";
    };
    date = "2024-06-04";
  };
  mako = {
    pname = "mako";
    version = "9dd088aa5f4529a3dd4d9760415e340664cb86df";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "mako";
      rev = "9dd088aa5f4529a3dd4d9760415e340664cb86df";
      fetchSubmodules = false;
      sha256 = "sha256-nUzWkQVsIH4rrCFSP87mXAka6P+Td2ifNbTuP7NM/SQ=";
    };
    date = "2023-08-12";
  };
  micro = {
    pname = "micro";
    version = "a67be21b9d2cf9f57911bb2cd9a6d8fb2c8d8e5a";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "micro";
      rev = "a67be21b9d2cf9f57911bb2cd9a6d8fb2c8d8e5a";
      fetchSubmodules = false;
      sha256 = "sha256-HFzcp3u9U3JrPqJdOYvjOTRDJA5bSE9lH6C5EmUmyrw=";
    };
    date = "2024-06-10";
  };
  mpv = {
    pname = "mpv";
    version = "6cbc49a38f23a4c3f3dc816e1d43389ca9675c1b";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "mpv";
      rev = "6cbc49a38f23a4c3f3dc816e1d43389ca9675c1b";
      fetchSubmodules = false;
      sha256 = "sha256-m+Zxfco4TYTdLWutC8eVKCVtt8VjJgN7FEqPiWlovE4=";
    };
    date = "2024-05-21";
  };
  neovim = {
    pname = "neovim";
    version = "31fcfb02c47952d5c75aec893b93b2878abe5fbb";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "31fcfb02c47952d5c75aec893b93b2878abe5fbb";
      fetchSubmodules = false;
      sha256 = "sha256-4hh1WXWJ2RdycyHXnXaYu4348JCtROlwPym0cAAdCFk=";
    };
    date = "2024-06-28";
  };
  palette = {
    pname = "palette";
    version = "7f17f46c5d3d86f4c8d17fef07d97459744e1157";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "palette";
      rev = "7f17f46c5d3d86f4c8d17fef07d97459744e1157";
      fetchSubmodules = false;
      sha256 = "sha256-3hX7MDaBPyFPTSoHlke0q1geNEdrOzlrIo9CMe2XUB0=";
    };
    date = "2024-06-12";
  };
  polybar = {
    pname = "polybar";
    version = "271885f11aeed2900d2fe54d6f37ea639a55da8c";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "polybar";
      rev = "271885f11aeed2900d2fe54d6f37ea639a55da8c";
      fetchSubmodules = false;
      sha256 = "sha256-BB2znvbE3o+paWECjN4aseUUj3Hnzv7z6IUHCbfvywU=";
    };
    date = "2024-05-19";
  };
  rio = {
    pname = "rio";
    version = "b94a931c2e2156c6b2a80decb1983d41da41a26c";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "rio";
      rev = "b94a931c2e2156c6b2a80decb1983d41da41a26c";
      fetchSubmodules = false;
      sha256 = "sha256-cN4wb+8t77p5hf5fiG0lc2NzBMcSsxYmmgd3iJcv65o=";
    };
    date = "2024-05-20";
  };
  rofi = {
    pname = "rofi";
    version = "b636a00fd40a7899a8206195464ae8b7f0450a6d";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "rofi";
      rev = "b636a00fd40a7899a8206195464ae8b7f0450a6d";
      fetchSubmodules = false;
      sha256 = "sha256-zA8Zum19pDTgn0KdQ0gD2kqCOXK4OCHBidFpGwrJOqg=";
    };
    date = "2024-06-20";
  };
  starship = {
    pname = "starship";
    version = "ca2fb0600730fd3958a2cb4d4ca97c401877b365";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "starship";
      rev = "ca2fb0600730fd3958a2cb4d4ca97c401877b365";
      fetchSubmodules = false;
      sha256 = "sha256-KzXO4dqpufxTew064ZLp3zKIXBwbF8Bi+I0Xa63j/lI=";
    };
    date = "2024-05-24";
  };
  sway = {
    pname = "sway";
    version = "9c430d7010d73444af5272a596e3a2c058612f71";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "sway";
      rev = "9c430d7010d73444af5272a596e3a2c058612f71";
      fetchSubmodules = false;
      sha256 = "sha256-EHZ/D4PrFqwyTpfcst3+hSx6z4saVD1M9CfFqnWI6io=";
    };
    date = "2024-04-03";
  };
  swaylock = {
    pname = "swaylock";
    version = "77246bbbbf8926bdb8962cffab6616bc2b9e8a06";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "swaylock";
      rev = "77246bbbbf8926bdb8962cffab6616bc2b9e8a06";
      fetchSubmodules = false;
      sha256 = "sha256-AKiOeV9ggvsreC/lq2qXytUsR+x66Q0kpN2F4/Oh2Ao=";
    };
    date = "2024-04-01";
  };
  tmux = {
    pname = "tmux";
    version = "e7cd05facc22c18fbab3f718d8ecd6494538fe38";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "tmux";
      rev = "e7cd05facc22c18fbab3f718d8ecd6494538fe38";
      fetchSubmodules = false;
      sha256 = "sha256-Sz5o4redRQYNiniwTeFhndGXerVBNGrza6GcKziLdQc=";
    };
    date = "2024-06-09";
  };
  tofi = {
    pname = "tofi";
    version = "d6106461867c077a5e1d25236e02b7be7c83839e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "tofi";
      rev = "d6106461867c077a5e1d25236e02b7be7c83839e";
      fetchSubmodules = false;
      sha256 = "sha256-urvt0ZuCe6iEtHwMUl4K6GDLQat/lV0TqgUOlKs8ykE=";
    };
    date = "2024-05-17";
  };
  yazi = {
    pname = "yazi";
    version = "9bfdccc2b78d7493fa5c5983bc176a0bc5fef164";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "yazi";
      rev = "9bfdccc2b78d7493fa5c5983bc176a0bc5fef164";
      fetchSubmodules = false;
      sha256 = "sha256-a2X9WToZmctD1HZVqN9A512iPd+3dtjRloBEifgteF4=";
    };
    date = "2024-06-16";
  };
  zathura = {
    pname = "zathura";
    version = "0adc53028d81bf047461bc61c43a484d11b15220";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "zathura";
      rev = "0adc53028d81bf047461bc61c43a484d11b15220";
      fetchSubmodules = false;
      sha256 = "sha256-/vD/hOi6KcaGyAp6Az7jL5/tQSGRzIrf0oHjAJf4QbI=";
    };
    date = "2024-04-04";
  };
}
