# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alacritty = {
    pname = "alacritty";
    version = "f6cb5a5c2b404cdaceaff193b9c52317f62c62f7";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "alacritty";
      rev = "f6cb5a5c2b404cdaceaff193b9c52317f62c62f7";
      fetchSubmodules = false;
      sha256 = "sha256-H8bouVCS46h0DgQ+oYY8JitahQDj0V9p2cOoD4cQX+Q=";
    };
    date = "2024-10-28";
  };
  bat = {
    pname = "bat";
    version = "d2bbee4f7e7d5bac63c054e4d8eca57954b31471";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bat";
      rev = "d2bbee4f7e7d5bac63c054e4d8eca57954b31471";
      fetchSubmodules = false;
      sha256 = "sha256-x1yqPCWuoBSx/cI94eA+AWwhiSA42cLNUOFJl7qjhmw=";
    };
    date = "2024-10-18";
  };
  bottom = {
    pname = "bottom";
    version = "ed09bd5a5dd78d83acdc8ff5fdec40a6340ed1c2";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bottom";
      rev = "ed09bd5a5dd78d83acdc8ff5fdec40a6340ed1c2";
      fetchSubmodules = false;
      sha256 = "sha256-Vi438I+YVvoD2xzq2t9hJ9R3a+2TlDdbakjFYFtjtXQ=";
    };
    date = "2024-09-17";
  };
  btop = {
    pname = "btop";
    version = "f437574b600f1c6d932627050b15ff5153b58fa3";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "btop";
      rev = "f437574b600f1c6d932627050b15ff5153b58fa3";
      fetchSubmodules = false;
      sha256 = "sha256-mEGZwScVPWGu+Vbtddc/sJ+mNdD2kKienGZVUcTSl+c=";
    };
    date = "2024-09-23";
  };
  cava = {
    pname = "cava";
    version = "0746f77974330338ee2e1e4d1ef9872eba57eb26";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "cava";
      rev = "0746f77974330338ee2e1e4d1ef9872eba57eb26";
      fetchSubmodules = false;
      sha256 = "sha256-5AQcCRGaAxP5KFzkJtkKFYq0Ug2xVIEqr2r/k87uWwY=";
    };
    date = "2024-09-04";
  };
  delta = {
    pname = "delta";
    version = "0674ec5114c08393d808e2516d153c7e6df00d41";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "delta";
      rev = "0674ec5114c08393d808e2516d153c7e6df00d41";
      fetchSubmodules = false;
      sha256 = "sha256-JvkTvAe1YltgmYSHeewzwg6xU38oGOIYoehXdHwW1zI=";
    };
    date = "2024-10-15";
  };
  dunst = {
    pname = "dunst";
    version = "f02cd2894411c9b4caa207cfd8ed6345f97c0455";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "dunst";
      rev = "f02cd2894411c9b4caa207cfd8ed6345f97c0455";
      fetchSubmodules = false;
      sha256 = "sha256-EadNqtF1m//blHkV660+d4YjDReVFU2Bzhs0Pb43jh4=";
    };
    date = "2024-07-20";
  };
  fcitx5 = {
    pname = "fcitx5";
    version = "3471b918d4b5aab2d3c3dd9f2c3b9c18fb470e8e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fcitx5";
      rev = "3471b918d4b5aab2d3c3dd9f2c3b9c18fb470e8e";
      fetchSubmodules = false;
      sha256 = "sha256-1IqFVTEY6z8yNjpi5C+wahMN1kpt0OJATy5echjPXmc=";
    };
    date = "2024-09-01";
  };
  fish = {
    pname = "fish";
    version = "cc8e4d8fffbdaab07b3979131030b234596f18da";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fish";
      rev = "cc8e4d8fffbdaab07b3979131030b234596f18da";
      fetchSubmodules = false;
      sha256 = "sha256-udiU2TOh0lYL7K7ylbt+BGlSDgCjMpy75vQ98C1kFcc=";
    };
    date = "2024-08-31";
  };
  foot = {
    pname = "foot";
    version = "962ff1a5b6387bc5419e9788a773a080eea5f1e1";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "foot";
      rev = "962ff1a5b6387bc5419e9788a773a080eea5f1e1";
      fetchSubmodules = false;
      sha256 = "sha256-eVH3BY2fZe0/OjqucM/IZthV8PMsM9XeIijOg8cNE1Y=";
    };
    date = "2024-09-25";
  };
  gh-dash = {
    pname = "gh-dash";
    version = "acb1b1c22446e34781731ddbfb5e9bd699eccc74";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "gh-dash";
      rev = "acb1b1c22446e34781731ddbfb5e9bd699eccc74";
      fetchSubmodules = false;
      sha256 = "sha256-fOCZxrEyWLi+VYnx3QYOP1R+VBhllhOlnO5/5Wg5aq4=";
    };
    date = "2024-10-30";
  };
  gitui = {
    pname = "gitui";
    version = "c7661f043cb6773a1fc96c336738c6399de3e617";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "gitui";
      rev = "c7661f043cb6773a1fc96c336738c6399de3e617";
      fetchSubmodules = false;
      sha256 = "sha256-CRxpEDShQcCEYtSXwLV5zFB8u0HVcudNcMruPyrnSEk=";
    };
    date = "2024-05-25";
  };
  glamour = {
    pname = "glamour";
    version = "f410083af1e9b2418bcd73dbbbc987461d4aa292";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "glamour";
      rev = "f410083af1e9b2418bcd73dbbbc987461d4aa292";
      fetchSubmodules = false;
      sha256 = "sha256-a7yR19KcxIS4UPhuhB+X0B+s8D5eytw0/EB0X4z46kA=";
    };
    date = "2024-07-13";
  };
  grub = {
    pname = "grub";
    version = "ffcceb344e2bc86adc8e64437459c1f38adf5b63";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "grub";
      rev = "ffcceb344e2bc86adc8e64437459c1f38adf5b63";
      fetchSubmodules = false;
      sha256 = "sha256-bDw+W69jeSiE1VBdQqqaeZf7OqCN7q5XYJ5+94PILXE=";
    };
    date = "2024-10-19";
  };
  gtk = {
    pname = "gtk";
    version = "23b52b5b9cde1e11c07315e79a55804d2ac77e3a";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "gtk";
      rev = "23b52b5b9cde1e11c07315e79a55804d2ac77e3a";
      fetchSubmodules = false;
      sha256 = "sha256-4tBGN+Rra6C2pjkoLWmNqaYUwpzALsYrn4tkYGUtQl4=";
    };
    date = "2024-06-02";
  };
  helix = {
    pname = "helix";
    version = "53a4de781d7f925105aa5ee9b9a4d892d89b5e86";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "helix";
      rev = "53a4de781d7f925105aa5ee9b9a4d892d89b5e86";
      fetchSubmodules = false;
      sha256 = "sha256-f8kcxtqI1UMVs2JATB+Prsgfwu3ew3jvZTEOLivUbmE=";
    };
    date = "2024-11-12";
  };
  hyprland = {
    pname = "hyprland";
    version = "c388ac55563ddeea0afe9df79d4bfff0096b146b";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "hyprland";
      rev = "c388ac55563ddeea0afe9df79d4bfff0096b146b";
      fetchSubmodules = false;
      sha256 = "sha256-xSa/z0Pu+ioZ0gFH9qSo9P94NPkEMovstm1avJ7rvzM=";
    };
    date = "2024-06-19";
  };
  imv = {
    pname = "imv";
    version = "0317a097b6ec8122b1da6d02f61d0c5158019f6e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "imv";
      rev = "0317a097b6ec8122b1da6d02f61d0c5158019f6e";
      fetchSubmodules = false;
      sha256 = "sha256-n6obxM5iVSOdlGdI8ZEmYuxudarLoZHqGETrpTcdrok=";
    };
    date = "2024-01-17";
  };
  k9s = {
    pname = "k9s";
    version = "fdbec82284744a1fc2eb3e2d24cb92ef87ffb8b4";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "k9s";
      rev = "fdbec82284744a1fc2eb3e2d24cb92ef87ffb8b4";
      fetchSubmodules = false;
      sha256 = "sha256-9h+jyEO4w0OnzeEKQXJbg9dvvWGZYQAO4MbgDn6QRzM=";
    };
    date = "2024-07-20";
  };
  kitty = {
    pname = "kitty";
    version = "b14e8385c827f2d41660b71c7fec1e92bdcf2676";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "kitty";
      rev = "b14e8385c827f2d41660b71c7fec1e92bdcf2676";
      fetchSubmodules = false;
      sha256 = "sha256-59ON7CzVgfZUo7F81qQZQ1r6kpcjR3OPvTl99gzDP8E=";
    };
    date = "2024-11-10";
  };
  lazygit = {
    pname = "lazygit";
    version = "d3c95a67ea3f778f7705d8ef814f87ac5213436d";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "lazygit";
      rev = "d3c95a67ea3f778f7705d8ef814f87ac5213436d";
      fetchSubmodules = false;
      sha256 = "sha256-b2SoIeXT1BaoxvEeQ0VaPmnBND+7qUe342kOIkyOcAc=";
    };
    date = "2024-10-14";
  };
  mako = {
    pname = "mako";
    version = "92844f144e72f2dc8727879ec141ffdacf3ff6a1";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "mako";
      rev = "92844f144e72f2dc8727879ec141ffdacf3ff6a1";
      fetchSubmodules = false;
      sha256 = "sha256-jgiZ+CrM4DX2nZR5BjjD9/Rk5CGGUy3gq9CCvYzp5Vs=";
    };
    date = "2024-08-30";
  };
  micro = {
    pname = "micro";
    version = "2802b32308e5b1a827689c095f11ae604bbc85e6";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "micro";
      rev = "2802b32308e5b1a827689c095f11ae604bbc85e6";
      fetchSubmodules = false;
      sha256 = "sha256-+Jf32S2CHackdmx+UmEKjx71ZCf4VfnxeA3yzz3MSLQ=";
    };
    date = "2024-09-08";
  };
  mpv = {
    pname = "mpv";
    version = "8d82ef42bde7cc7cc4fad7ce690aa90feab46f34";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "mpv";
      rev = "8d82ef42bde7cc7cc4fad7ce690aa90feab46f34";
      fetchSubmodules = false;
      sha256 = "sha256-l5s9WTxNlI4glAYnbfPZ6K8O3knf5zzgDfOKwFxl/jQ=";
    };
    date = "2024-11-13";
  };
  neovim = {
    pname = "neovim";
    version = "637d99e638bc6f1efedac582f6ccab08badac0c6";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "637d99e638bc6f1efedac582f6ccab08badac0c6";
      fetchSubmodules = false;
      sha256 = "sha256-lsnePejThsEygTCKV/rfJJ/h+RSrro91am841iznJe4=";
    };
    date = "2024-11-10";
  };
  palette = {
    pname = "palette";
    version = "b85d36adec22631684ae64ced0a5cdd15462de3b";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "palette";
      rev = "b85d36adec22631684ae64ced0a5cdd15462de3b";
      fetchSubmodules = false;
      sha256 = "sha256-8AZVLJq5fKbMd/YFbqwgpHB7p4iTPTIMmC39R+3ZZ80=";
    };
    date = "2024-11-07";
  };
  polybar = {
    pname = "polybar";
    version = "20054f39d3b77bd1afc765981a42c3467bf91204";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "polybar";
      rev = "20054f39d3b77bd1afc765981a42c3467bf91204";
      fetchSubmodules = false;
      sha256 = "sha256-jMQ+gH1djp2euERZpVW9muHQFI7xYnEQoNpucRj7Gow=";
    };
    date = "2024-07-20";
  };
  rio = {
    pname = "rio";
    version = "6d93b3385a0f2ae586edc30aa64601d40ea382d5";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "rio";
      rev = "6d93b3385a0f2ae586edc30aa64601d40ea382d5";
      fetchSubmodules = false;
      sha256 = "sha256-8cbySVryZQTUtogpiuMca+ANhtQjLS8AyvfngIVZN5w=";
    };
    date = "2024-07-12";
  };
  rofi = {
    pname = "rofi";
    version = "b636a00fd40a7899a8206195464ae8b7f0450a6d";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "rofi";
      rev = "b636a00fd40a7899a8206195464ae8b7f0450a6d";
      fetchSubmodules = false;
      sha256 = "sha256-zA8Zum19pDTgn0KdQ0gD2kqCOXK4OCHBidFpGwrJOqg=";
    };
    date = "2024-06-20";
  };
  starship = {
    pname = "starship";
    version = "31b224a6408015d1e17a5766de6b764cf9af3c1c";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "starship";
      rev = "31b224a6408015d1e17a5766de6b764cf9af3c1c";
      fetchSubmodules = false;
      sha256 = "sha256-TjcoBlgmRoqXKdXH/eC5dWk7uqUSkvyV4ir9WqFR1pY=";
    };
    date = "2024-11-11";
  };
  sway = {
    pname = "sway";
    version = "c072ada05271eec960dc893affe9ac55af63a745";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "sway";
      rev = "c072ada05271eec960dc893affe9ac55af63a745";
      fetchSubmodules = false;
      sha256 = "sha256-H+ZueiYkCoBfS8JENLKhL/efFK6WFNDsbiMbTpGROUs=";
    };
    date = "2024-10-14";
  };
  swaylock = {
    pname = "swaylock";
    version = "77246bbbbf8926bdb8962cffab6616bc2b9e8a06";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "swaylock";
      rev = "77246bbbbf8926bdb8962cffab6616bc2b9e8a06";
      fetchSubmodules = false;
      sha256 = "sha256-AKiOeV9ggvsreC/lq2qXytUsR+x66Q0kpN2F4/Oh2Ao=";
    };
    date = "2024-04-01";
  };
  tmux = {
    pname = "tmux";
    version = "eb78ade9dc1f6cd8ba654572f51ddcae3c6e7fd7";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "tmux";
      rev = "eb78ade9dc1f6cd8ba654572f51ddcae3c6e7fd7";
      fetchSubmodules = false;
      sha256 = "sha256-f3mBAkE32vjekOa9iPzuYp5cTSl0ZnHd5ixHjQBpbqY=";
    };
    date = "2024-11-14";
  };
  tofi = {
    pname = "tofi";
    version = "d6106461867c077a5e1d25236e02b7be7c83839e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "tofi";
      rev = "d6106461867c077a5e1d25236e02b7be7c83839e";
      fetchSubmodules = false;
      sha256 = "sha256-urvt0ZuCe6iEtHwMUl4K6GDLQat/lV0TqgUOlKs8ykE=";
    };
    date = "2024-05-17";
  };
  yazi = {
    pname = "yazi";
    version = "54d868433a0c2f3e1651114136ea088eef72a4a7";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "yazi";
      rev = "54d868433a0c2f3e1651114136ea088eef72a4a7";
      fetchSubmodules = false;
      sha256 = "sha256-dMXSXS3Scj1LZZqqnvvC37VWSyjSQZg9thvjcm2iNSM=";
    };
    date = "2024-10-26";
  };
  zathura = {
    pname = "zathura";
    version = "0adc53028d81bf047461bc61c43a484d11b15220";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "zathura";
      rev = "0adc53028d81bf047461bc61c43a484d11b15220";
      fetchSubmodules = false;
      sha256 = "sha256-/vD/hOi6KcaGyAp6Az7jL5/tQSGRzIrf0oHjAJf4QbI=";
    };
    date = "2024-04-04";
  };
}
